// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"6fe3647b927b27b57b138125ab8aca4186294d4cd21b6a19e75330db523ab303aec3e4345484229ff2396158e201871063130e439f9e04ed5d64bb38bb2724fd"}}
];
